# -*- coding: utf-8 -*-
"""ch02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aFKXaaMxM-HoQZe2sQ016qVHikahVW6V
"""

# 파이썬 수업2

"""###### H6
- h1
-----------------

[google](https://google.com, "google link")

This is an H1
=============
This is an H2
-------------
# This is a H1
## This is a H2
### This is a H3
#### This is a H4
##### This is a H5
###### This is a H6
> This is a first blockqute.
>	> This is a second blockqute.
>	>	> This is a third blockqute.
1. 첫번째
3. 세번째
2. 두번째
* 빨강
  * 녹색
    * 파랑

+ 빨강
  + 녹색
    + 파랑

- 빨강
  - 녹색
    - 파랑
```
print("hello world")
```
"""

a=[1,2,3,4]

a.append(0) #. 입력후 ctrl+space로 사용할 수 있는 메소드와 인스턴스 확인 가능

def add_fun(a,b):
  return a+b

add_fun(1,4)

add_fun("hello","world")

add_fun?

# Commented out IPython magic to ensure Python compatibility.
# %pwd

2**20

_+1

abs(-4)

"""# 변수에 값 대입
- 변수 선언시에 자료형을 명시하지 않아도 된다.
- 변수에 값을 대입하면 그 값의 자료형에 따라 자료형이 동적으로 결정
"""

number=1
pi=3.14
flag = True
char = 'x'
chars = 'hello'

print(type(number))
print(type(pi))
print(type(flag))
print(type(char))
print(type(chars))

1j * 1j #complax num

a=13
b=29

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)
print(a**b)

if a==b : print("a")
if a!=b : print("b")
if a<b : print("c")
if a<=b : print("d")
if a>=b : print("e")
if a>b : print("f")

head = "나는"
tail = "배고프다"
head+tail

a=1
b=1.0
c=3
type(a*b)
type(a+b)
type(a+c)

str_8="Python"

str_8[0]

str_8[4]

str_8[0:4]

"나의 이름은 %s 입니다." %"정병길"

name = input("이름이 뭐에요?")

year = input("태어난 연도를 입력하세요 : ")
year = int(year)
age = 2022-year+1
print("나의 나이는 %d" %age)

name = input("이름을 입력해주세요 : ")
year = int(input("태어난 연도를 입력해주세요 :"))
age = 2022 - year
print("나의 이름은 %s 이고, 나이는 %d 입니다." %(name, age))

name = input("이름을 입력해주세요 : ")
year = int(input("태어난 연도를 입력해주세요 :"))
age = 2022 - year
print("나의 이름은 {} 이고, 나이는 {} 입니다.".format(name, age))

name = input("이름을 입력해주세요 : ")
year = int(input("태어난 연도를 입력해주세요 :"))
age = 2022 - year
print(f"나의 이름은 {name} 이고, 나이는 {age} 세입니다.")

a="Python is soo funny!"
b=","
print(a.count("n"))
print(a.find("s"))
print(a.index("i"))
print(b.join(a))
print(a.upper())
print(a.lower())
print(a.replace("soo","really"))
print(a.split())

